// ------------------------------------------------------------
// Seed script — fills the database with sample products across
// every store section (unstitched, pret, collections, fragrances,
// accessories, sale). Run:  npm run seed
// All names, text and images here are original placeholders.
// Replace the placehold.co images with real product photos.
// ------------------------------------------------------------

require('dotenv').config();

const mongoose = require('mongoose');
const Product = require('./models/Product');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/libaas';

// Helper to build a placeholder image URL
function img(text, bg = 'E8DCCF', fg = '5C4A3A') {
  return `https://placehold.co/600x800/${bg}/${fg}?text=${encodeURIComponent(text)}`;
}

const SIZES_STITCHED = ['XS', 'S', 'M', 'L', 'XL'];
const SIZES_UNSTITCHED = ['Unstitched'];

const products = [
  // ---------------- Unstitched ----------------
  {
    name: 'Gulbahar Embroidered Lawn 3-Piece',
    price: 4899,
    oldPrice: 5999,
    category: 'unstitched-embroidered',
    sku: 'LB-UN-001',
    sizes: SIZES_UNSTITCHED,
    colors: ['Maroon', 'Teal'],
    images: [img('Gulbahar+Lawn'), img('Gulbahar+Lawn+2')],
    description: 'Three-piece unstitched lawn with delicate front embroidery, printed dupatta and dyed cambric trouser.',
    fabric: 'Premium Lawn',
    care: 'Machine wash cold, do not bleach, dry in shade.',
    stock: 40,
    isNew: true,
    rating: 4.5,
  },
  {
    name: 'Printed Khaddar Winter 3-Piece',
    price: 4499,
    oldPrice: null,
    category: 'unstitched-printed',
    sku: 'LB-UN-002',
    sizes: SIZES_UNSTITCHED,
    colors: ['Mustard', 'Olive'],
    images: [img('Khaddar+Suit')],
    description: 'Warm khaddar three-piece with all-over print, ideal for the winter season.',
    fabric: 'Khaddar',
    care: 'Machine wash cold with like colours.',
    stock: 35,
    isNew: false,
    rating: 4.2,
  },
  {
    name: 'Summer Breeze Lawn Shirt Piece',
    price: 1899,
    oldPrice: 2299,
    category: 'unstitched-summer',
    sku: 'LB-UN-003',
    sizes: SIZES_UNSTITCHED,
    colors: ['Sky Blue', 'Peach'],
    images: [img('Summer+Lawn+Shirt')],
    description: 'Light single shirt piece in breathable summer lawn with a fresh floral print.',
    fabric: 'Swiss Lawn',
    care: 'Gentle machine wash, dry in shade.',
    stock: 60,
    isNew: true,
    rating: 4.6,
  },
  {
    name: 'Chandni Luxury Lawn 3-Piece',
    price: 6499,
    oldPrice: null,
    category: 'unstitched-lawn',
    sku: 'LB-UN-004',
    sizes: SIZES_UNSTITCHED,
    colors: ['Ivory', 'Mint'],
    images: [img('Chandni+Lawn')],
    description: 'Premium lawn three-piece with embroidered neckline and woven jacquard dupatta.',
    fabric: 'Luxury Lawn',
    care: 'Dry clean recommended for embroidered panels.',
    stock: 25,
    isNew: true,
    rating: 4.8,
  },

  // ---------------- Ready to wear / Pret ----------------
  {
    name: 'Rose Embroidered Pret Kurti',
    price: 3299,
    oldPrice: 3999,
    category: 'pret-embroidered',
    sku: 'LB-PR-001',
    sizes: SIZES_STITCHED,
    colors: ['Rose Pink', 'White'],
    images: [img('Rose+Kurti'), img('Rose+Kurti+2')],
    description: 'Ready-to-wear straight kurti with thread embroidery on the neckline and sleeves.',
    fabric: 'Cotton Silk',
    care: 'Machine wash cold, iron on reverse.',
    stock: 30,
    isNew: true,
    rating: 4.4,
  },
  {
    name: 'Floral Printed Two-Piece Set',
    price: 3799,
    oldPrice: null,
    category: 'pret-printed',
    sku: 'LB-PR-002',
    sizes: SIZES_STITCHED,
    colors: ['Blue', 'Yellow'],
    images: [img('Floral+Set')],
    description: 'Printed shirt with matching straight trouser — an easy everyday two-piece.',
    fabric: 'Cambric Cotton',
    care: 'Machine wash cold.',
    stock: 28,
    isNew: false,
    rating: 4.3,
  },
  {
    name: 'Essential Solid Kurta — Charcoal',
    price: 2499,
    oldPrice: null,
    category: 'pret-solids',
    sku: 'LB-PR-003',
    sizes: SIZES_STITCHED,
    colors: ['Charcoal', 'Black', 'Beige'],
    images: [img('Solid+Kurta')],
    description: 'Wardrobe essential: a clean solid kurta in soft breathable fabric.',
    fabric: 'Lawn Cotton',
    care: 'Machine wash cold.',
    stock: 50,
    isNew: false,
    rating: 4.1,
  },
  {
    name: 'Sage Co-Ord Set',
    price: 4599,
    oldPrice: 5499,
    category: 'pret-coords',
    sku: 'LB-PR-004',
    sizes: SIZES_STITCHED,
    colors: ['Sage Green'],
    images: [img('Sage+Coord')],
    description: 'Matching shirt and wide-leg trouser co-ord set in a calm sage tone.',
    fabric: 'Crepe',
    care: 'Gentle wash, cool iron.',
    stock: 22,
    isNew: true,
    rating: 4.7,
  },
  {
    name: 'Mehfil Festive Chiffon Suit',
    price: 8999,
    oldPrice: 10999,
    category: 'pret-festive',
    sku: 'LB-PR-005',
    sizes: SIZES_STITCHED,
    colors: ['Deep Red', 'Emerald'],
    images: [img('Festive+Suit'), img('Festive+Suit+2')],
    description: 'Festive three-piece in flowing chiffon with sequin spray and embroidered dupatta.',
    fabric: 'Chiffon',
    care: 'Dry clean only.',
    stock: 15,
    isNew: true,
    rating: 4.9,
  },
  {
    name: 'Everyday Straight Kurti — White',
    price: 1999,
    oldPrice: 2499,
    category: 'pret-kurtis',
    sku: 'LB-PR-006',
    sizes: SIZES_STITCHED,
    colors: ['White', 'Black'],
    images: [img('White+Kurti')],
    description: 'Simple straight-cut kurti for daily wear, side slits and 3/4 sleeves.',
    fabric: 'Cotton',
    care: 'Machine wash cold.',
    stock: 70,
    isNew: false,
    rating: 4.0,
  },
  {
    name: 'Tailored Straight Trouser',
    price: 1499,
    oldPrice: null,
    category: 'pret-bottoms',
    sku: 'LB-PR-007',
    sizes: SIZES_STITCHED,
    colors: ['Black', 'Off White'],
    images: [img('Straight+Trouser')],
    description: 'Clean tailored straight trouser with elasticated back waist.',
    fabric: 'Cotton Blend',
    care: 'Machine wash cold.',
    stock: 45,
    isNew: false,
    rating: 4.2,
  },
  {
    name: 'Classic Men Kurta — Navy',
    price: 2999,
    oldPrice: 3499,
    category: 'men-pret',
    sku: 'LB-MN-001',
    sizes: SIZES_STITCHED,
    colors: ['Navy', 'White', 'Grey'],
    images: [img('Men+Kurta'), img('Men+Kurta+2')],
    description: 'Classic menswear kurta with band collar and side slits, in soft wash-and-wear.',
    fabric: 'Wash & Wear',
    care: 'Machine wash cold.',
    stock: 40,
    isNew: true,
    rating: 4.5,
  },

  // ---------------- Collections ----------------
  {
    name: 'Signature Embroidered Ensemble',
    price: 12999,
    oldPrice: null,
    category: 'signature',
    sku: 'LB-SG-001',
    sizes: SIZES_STITCHED,
    colors: ['Champagne', 'Blush'],
    images: [img('Signature+Look'), img('Signature+Look+2')],
    description: 'Our flagship signature look — hand-finished embroidery on luxe fabric with a statement dupatta.',
    fabric: 'Raw Silk',
    care: 'Dry clean only.',
    stock: 10,
    isNew: true,
    rating: 5.0,
  },
  {
    name: 'Shamoz Silk Saree — Teal',
    price: 7499,
    oldPrice: 8999,
    category: 'silk',
    sku: 'LB-SL-001',
    sizes: ['One Size'],
    colors: ['Teal', 'Plum'],
    images: [img('Silk+Saree')],
    description: 'Six yards of lustrous shamoz silk with a woven border and unstitched blouse piece.',
    fabric: 'Shamoz Silk',
    care: 'Dry clean only.',
    stock: 18,
    isNew: true,
    rating: 4.7,
  },
  {
    name: 'Urban Western Denim Jacket',
    price: 3999,
    oldPrice: null,
    category: 'western',
    sku: 'LB-WS-001',
    sizes: SIZES_STITCHED,
    colors: ['Blue Denim'],
    images: [img('Denim+Jacket')],
    description: 'Classic-fit denim jacket with button front — an easy western layer.',
    fabric: 'Denim',
    care: 'Machine wash cold, wash inside out.',
    stock: 26,
    isNew: false,
    rating: 4.3,
  },

  // ---------------- Fragrances ----------------
  {
    name: 'Ameer Oud — Men 100ml',
    price: 3499,
    oldPrice: 4299,
    category: 'fragrance-men',
    sku: 'LB-FR-001',
    sizes: ['100ml'],
    colors: [],
    images: [img('Oud+Perfume')],
    description: 'Bold oud and amber eau de parfum for men, long-lasting with a warm dry-down.',
    fabric: '',
    care: 'Store away from direct sunlight.',
    stock: 30,
    isNew: true,
    rating: 4.6,
  },
  {
    name: 'Noor Bloom — Women 100ml',
    price: 3299,
    oldPrice: null,
    category: 'fragrance-women',
    sku: 'LB-FR-002',
    sizes: ['100ml'],
    colors: [],
    images: [img('Floral+Perfume')],
    description: 'Fresh floral-fruity eau de parfum with jasmine heart and musk base.',
    fabric: '',
    care: 'Store away from direct sunlight.',
    stock: 32,
    isNew: true,
    rating: 4.5,
  },

  // ---------------- Accessories ----------------
  {
    name: 'Woven Tote Bag — Tan',
    price: 2499,
    oldPrice: 2999,
    category: 'acc-bags',
    sku: 'LB-AC-001',
    sizes: ['One Size'],
    colors: ['Tan', 'Black'],
    images: [img('Tote+Bag')],
    description: 'Spacious woven-look tote with inner zip pocket and magnetic closure.',
    fabric: 'Faux Leather',
    care: 'Wipe clean with a damp cloth.',
    stock: 24,
    isNew: true,
    rating: 4.4,
  },
  {
    name: 'Pearl Drop Earrings',
    price: 999,
    oldPrice: 1299,
    category: 'acc-jewelry',
    sku: 'LB-AC-002',
    sizes: ['One Size'],
    colors: ['Gold'],
    images: [img('Pearl+Earrings')],
    description: 'Elegant gold-tone drop earrings with faux pearl detailing.',
    fabric: '',
    care: 'Keep dry, store in pouch.',
    stock: 55,
    isNew: false,
    rating: 4.3,
  },
  {
    name: 'Embroidered Net Dupatta',
    price: 1799,
    oldPrice: null,
    category: 'acc-dupattas',
    sku: 'LB-AC-003',
    sizes: ['2.5 Yards'],
    colors: ['Red', 'Green', 'Black'],
    images: [img('Net+Dupatta')],
    description: 'Lightweight net dupatta with all-over embroidery and scalloped border.',
    fabric: 'Net',
    care: 'Gentle hand wash.',
    stock: 38,
    isNew: true,
    rating: 4.5,
  },
  {
    name: 'Pashmina Shawl — Grey',
    price: 2199,
    oldPrice: 2799,
    category: 'acc-shawls',
    sku: 'LB-AC-004',
    sizes: ['One Size'],
    colors: ['Grey', 'Beige'],
    images: [img('Pashmina+Shawl')],
    description: 'Soft pashmina-feel shawl with a subtle woven border.',
    fabric: 'Pashmina Blend',
    care: 'Dry clean recommended.',
    stock: 30,
    isNew: false,
    rating: 4.6,
  },
  {
    name: 'Classic Leather Strap Watch',
    price: 4999,
    oldPrice: 5999,
    category: 'acc-watches',
    sku: 'LB-AC-005',
    sizes: ['One Size'],
    colors: ['Brown', 'Black'],
    images: [img('Leather+Watch')],
    description: 'Minimal dial watch with genuine-style leather strap and quartz movement.',
    fabric: '',
    care: 'Keep away from water.',
    stock: 20,
    isNew: true,
    rating: 4.7,
  },
  {
    name: 'Aviator Sunglasses',
    price: 1899,
    oldPrice: null,
    category: 'acc-sunglasses',
    sku: 'LB-AC-006',
    sizes: ['One Size'],
    colors: ['Gold', 'Black'],
    images: [img('Aviator+Shades')],
    description: 'Timeless aviator frame with UV-protected tinted lenses.',
    fabric: '',
    care: 'Clean with microfiber cloth.',
    stock: 42,
    isNew: false,
    rating: 4.2,
  },
  {
    name: 'Block Heel Sandals — Nude',
    price: 2799,
    oldPrice: 3299,
    category: 'acc-footwear',
    sku: 'LB-AC-007',
    sizes: ['36', '37', '38', '39', '40', '41'],
    colors: ['Nude', 'Black'],
    images: [img('Heel+Sandals')],
    description: 'Comfortable block-heel sandals with cushioned sole for all-day wear.',
    fabric: 'Faux Leather',
    care: 'Wipe clean.',
    stock: 28,
    isNew: true,
    rating: 4.4,
  },
  {
    name: 'Printed Silk Scarf',
    price: 1299,
    oldPrice: null,
    category: 'acc-scarves',
    sku: 'LB-AC-008',
    sizes: ['One Size'],
    colors: ['Multi'],
    images: [img('Silk+Scarf')],
    description: 'Lightweight printed scarf in a silky finish — wear it many ways.',
    fabric: 'Silk Blend',
    care: 'Gentle hand wash.',
    stock: 48,
    isNew: false,
    rating: 4.1,
  },
  {
    name: 'Pearl Hair Claw Set (3 pcs)',
    price: 699,
    oldPrice: 899,
    category: 'acc-hair',
    sku: 'LB-AC-009',
    sizes: ['One Size'],
    colors: ['Pearl White'],
    images: [img('Hair+Claws')],
    description: 'Set of three pearl-finish hair claw clips in different sizes.',
    fabric: '',
    care: 'Wipe clean.',
    stock: 65,
    isNew: true,
    rating: 4.3,
  },
  {
    name: 'Woolen Muffler — Maroon',
    price: 1199,
    oldPrice: null,
    category: 'acc-mufflers',
    sku: 'LB-AC-010',
    sizes: ['One Size'],
    colors: ['Maroon', 'Navy'],
    images: [img('Wool+Muffler')],
    description: 'Warm knitted woolen muffler with fringed ends.',
    fabric: 'Wool Blend',
    care: 'Hand wash cold.',
    stock: 36,
    isNew: false,
    rating: 4.0,
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');

    await Product.deleteMany({});
    console.log('Cleared existing products');

    // insertMany skips the pre('save') hook, so build each slug here
    // using the same rule as the Product model.
    const withSlugs = products.map((p) => {
      const slug = p.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '');
      return {
        ...p,
        slug,
        // Real product photos live in the frontend's public folder and
        // are served from the site root, so a relative path is enough.
        images: [`/images/products/${slug}.jpg`],
      };
    });

    const created = await Product.insertMany(withSlugs);
    console.log(`Seeded ${created.length} products`);
  } catch (err) {
    console.error('Seed failed:', err.message);
    process.exit(1);
  } finally {
    await mongoose.disconnect();
  }
}

seed();
